force-app/main/default/objects/Countries__c/Countries__c.object-meta.xml
<CustomObject>
    <label>Countries</label>
    <nameField>
        <label>Countries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Countries__c.field-meta.xml
<CustomField>
    <fullName>Countries__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Countries</label>
    <referenceTo>Countries__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Wishlist__c/Wishlist__c.object-meta.xml
<CustomObject>
    <label>Wishlist</label>
    <nameField>
        <label>Wishlist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wishlists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/WishlistViewApexController.cls
public class WishlistViewApexController {
    
    public static List<Wishlist__c> wishlist = [SELECT Name FROM Wishlist__c];
    
    @AuraEnabled
    public static List<Wishlist__c> getWishlist() {
        return wishlist;
    }
    
    @AuraEnabled
    public static List<Service__c> getServices() {
        List<Service__c> serviceList = new List<Service__c>();
        for (Wishlist__c w : wishlist) {
            List<Service__c> loopList = [SELECT Name FROM Service__c
                                         WHERE Countries__r.Name LIKE :w.Name];
            for (Service__c s : loopList) {
                serviceList.add(s);
            }
        }
        system.debug(serviceList);
        for (Service__c s : serviceList) {
            system.debug(s.Name);
        }
        return serviceList;
    }
    
}